// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.1
// source: protobuf/teleproxy.proto

package protobuf

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TeleProxyClient is the client API for TeleProxy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TeleProxyClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	Listen(ctx context.Context, opts ...grpc.CallOption) (TeleProxy_ListenClient, error)
	Deregister(ctx context.Context, in *DeregisterRequest, opts ...grpc.CallOption) (*DeregisterResponse, error)
	Dump(ctx context.Context, in *DumpRequest, opts ...grpc.CallOption) (*DumpResponse, error)
}

type teleProxyClient struct {
	cc grpc.ClientConnInterface
}

func NewTeleProxyClient(cc grpc.ClientConnInterface) TeleProxyClient {
	return &teleProxyClient{cc}
}

func (c *teleProxyClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, "/TeleProxy/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teleProxyClient) Listen(ctx context.Context, opts ...grpc.CallOption) (TeleProxy_ListenClient, error) {
	stream, err := c.cc.NewStream(ctx, &TeleProxy_ServiceDesc.Streams[0], "/TeleProxy/Listen", opts...)
	if err != nil {
		return nil, err
	}
	x := &teleProxyListenClient{stream}
	return x, nil
}

type TeleProxy_ListenClient interface {
	Send(*HttpResponse) error
	Recv() (*HttpRequest, error)
	grpc.ClientStream
}

type teleProxyListenClient struct {
	grpc.ClientStream
}

func (x *teleProxyListenClient) Send(m *HttpResponse) error {
	return x.ClientStream.SendMsg(m)
}

func (x *teleProxyListenClient) Recv() (*HttpRequest, error) {
	m := new(HttpRequest)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *teleProxyClient) Deregister(ctx context.Context, in *DeregisterRequest, opts ...grpc.CallOption) (*DeregisterResponse, error) {
	out := new(DeregisterResponse)
	err := c.cc.Invoke(ctx, "/TeleProxy/Deregister", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teleProxyClient) Dump(ctx context.Context, in *DumpRequest, opts ...grpc.CallOption) (*DumpResponse, error) {
	out := new(DumpResponse)
	err := c.cc.Invoke(ctx, "/TeleProxy/Dump", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TeleProxyServer is the server API for TeleProxy service.
// All implementations must embed UnimplementedTeleProxyServer
// for forward compatibility
type TeleProxyServer interface {
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	Listen(TeleProxy_ListenServer) error
	Deregister(context.Context, *DeregisterRequest) (*DeregisterResponse, error)
	Dump(context.Context, *DumpRequest) (*DumpResponse, error)
	mustEmbedUnimplementedTeleProxyServer()
}

// UnimplementedTeleProxyServer must be embedded to have forward compatible implementations.
type UnimplementedTeleProxyServer struct {
}

func (UnimplementedTeleProxyServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedTeleProxyServer) Listen(TeleProxy_ListenServer) error {
	return status.Errorf(codes.Unimplemented, "method Listen not implemented")
}
func (UnimplementedTeleProxyServer) Deregister(context.Context, *DeregisterRequest) (*DeregisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Deregister not implemented")
}
func (UnimplementedTeleProxyServer) Dump(context.Context, *DumpRequest) (*DumpResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Dump not implemented")
}
func (UnimplementedTeleProxyServer) mustEmbedUnimplementedTeleProxyServer() {}

// UnsafeTeleProxyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TeleProxyServer will
// result in compilation errors.
type UnsafeTeleProxyServer interface {
	mustEmbedUnimplementedTeleProxyServer()
}

func RegisterTeleProxyServer(s grpc.ServiceRegistrar, srv TeleProxyServer) {
	s.RegisterService(&TeleProxy_ServiceDesc, srv)
}

func _TeleProxy_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeleProxyServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TeleProxy/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeleProxyServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeleProxy_Listen_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TeleProxyServer).Listen(&teleProxyListenServer{stream})
}

type TeleProxy_ListenServer interface {
	Send(*HttpRequest) error
	Recv() (*HttpResponse, error)
	grpc.ServerStream
}

type teleProxyListenServer struct {
	grpc.ServerStream
}

func (x *teleProxyListenServer) Send(m *HttpRequest) error {
	return x.ServerStream.SendMsg(m)
}

func (x *teleProxyListenServer) Recv() (*HttpResponse, error) {
	m := new(HttpResponse)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _TeleProxy_Deregister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeregisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeleProxyServer).Deregister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TeleProxy/Deregister",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeleProxyServer).Deregister(ctx, req.(*DeregisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeleProxy_Dump_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DumpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeleProxyServer).Dump(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TeleProxy/Dump",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeleProxyServer).Dump(ctx, req.(*DumpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TeleProxy_ServiceDesc is the grpc.ServiceDesc for TeleProxy service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TeleProxy_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "TeleProxy",
	HandlerType: (*TeleProxyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _TeleProxy_Register_Handler,
		},
		{
			MethodName: "Deregister",
			Handler:    _TeleProxy_Deregister_Handler,
		},
		{
			MethodName: "Dump",
			Handler:    _TeleProxy_Dump_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Listen",
			Handler:       _TeleProxy_Listen_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "protobuf/teleproxy.proto",
}
